version: '3.8'

services:
    weather_forecast_php_cli:
        image: php:7.4-cli
        build: ./docker/php
        tty: true
        working_dir: /var/www/html
        env_file: ./weather_forecast/.env.local
        volumes:
            - ./weather_forecast:/var/www/html